# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PickFoodDelivery' do
  
pod 'SnapKit', '~> 5.0.0'
pod 'Firebase/Auth'
pod 'Firebase/Database'

end
